//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelManagementOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int Musteri_İd { get; set; }
        public string TCNO { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Adress { get; set; }
        public string Cinsiyet { get; set; }
        public string TeleNum { get; set; }
        public string Sifre { get; set; }
        public string oda_numarasi { get; set; }
        public string yataklar { get; set; }
        public Nullable<int> fiyatlar { get; set; }
        public Nullable<System.DateTime> checkinTarihi { get; set; }
        public Nullable<System.DateTime> checkoutTarihi { get; set; }
        public Nullable<int> DogumTarihi { get; set; }
    }
}
