//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelManagementOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelView
    {
        public int PersonelID { get; set; }
        public int GorevId { get; set; }
        public Nullable<decimal> SicilNo { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
        public Nullable<int> DogumYil { get; set; }
        public string maas { get; set; }
        public string GorevAd { get; set; }
        public string GorevKodu { get; set; }
        public int Expr1 { get; set; }
    }
}
