//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelManagementOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunID { get; set; }
        public int KategoriId { get; set; }
        public string UrunAd { get; set; }
        public string BarkodNo { get; set; }
        public Nullable<int> UrunMiktari { get; set; }
        public Nullable<int> UrunFiyati { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
