//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelManagementOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunSati
    {
        public int UrunSatisID { get; set; }
        public decimal SatisMiktari { get; set; }
        public decimal SatisTutari { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public int PersonelId { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
